name: Node.js CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        #node-version: [12, 14, 16]
        node-verson: [12]  
        #os: [ubuntu-latest, windows-latest, macos-latest]
        os: [ windows-latest ]
        # See supported Node.js release schedule at https://nodejs.org/en/about/releases/

    steps:
    - uses: actions/checkout@v3
    - name: Use Node.js ${{ matrix.node-version }}
      uses: actions/setup-node@v3
      with:
        node-version: ${{ matrix.node-version }}
    - run: npm install
    
   
    - name: Agent Windows Zip
      if: ${{ matrix.os == 'windows-latest' }}   
      run: Compress-Archive -Path D:\a\_temp\*.* -DestinationPath D:\.zip -Force

    - name: Agent Linux Zip
      if: ${{ matrix.os == 'ubuntu-latest' }} 
      run: zip release.zip ./* -r

    - name: Agent MacOs Zip
      if: ${{ matrix.os == 'macos-latest' }} 
      run: zip release.zip ./* -r

    - name: Upload a Build Artifact
      uses: actions/upload-artifact@v3.0.0
      with:
        # Artifact name
        name: artifact
        # A file, directory or wildcard pattern that describes what to upload
        path: release.zip .
